import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Check, ChevronRight, Clock3, Flame, Lightbulb, Mic, NotebookPen, RotateCcw, Sparkles, SpellCheck, Target } from "lucide-react";
import { getDashboard } from "@/lib/dashboard";
import { prisma } from "@/lib/db";
import { PageTitle, StatCard } from "@/components/ui";
import { NextSession } from "@/components/dashboard/next-session";
import { ActivityChart } from "@/components/activity-chart";

export default async function Dashboard() {
  const [data, spotlight] = await Promise.all([getDashboard(), prisma.vocabularyWord.findUnique({ where: { word: "significant" } })]);
  const { settings, vocabulary, today, stats, streak } = data;
  const hour = Number(new Intl.DateTimeFormat("en", { hour: "numeric", hourCycle: "h23", timeZone: settings.timezone }).format(new Date()));
  const greeting = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";
  const completedModules = new Set(today.modulesPractised);
  const activities = [
    { title: "Build your vocabulary", description: `${settings.vocabularySessionSize} new words · English + Bangla`, href: `/vocabulary/learn?size=${settings.vocabularySessionSize}`, icon: BookOpen, color: "green", duration: "15 min", module: "VOCABULARY" },
    { title: "Read between the lines", description: "Original passage · Find the evidence", href: "/reading", icon: BookOpen, color: "blue", duration: "15 min", module: "READING" },
    { title: "Find your speaking voice", description: "A little practice in your own words", href: "/speaking", icon: Mic, color: "peach", duration: "10 min", module: "SPEAKING" },
    { title: "Put your ideas into words", description: "Plan, write, and reflect", href: "/writing", icon: NotebookPen, color: "purple", duration: "15 min", module: "WRITING" },
  ];
  const skills = [["Listening", settings.estimatedListening], ["Reading", settings.estimatedReading], ["Writing", settings.estimatedWriting], ["Speaking", settings.estimatedSpeaking]] as const;
  return <>
    <PageTitle title={`${greeting}, ${settings.name === "Learner" ? "learner" : settings.name.split(" ")[0]}.`} description="A fresh opportunity to get a little closer to your goal." action={<span className="date-label"><CalendarDays size={14}/>{new Intl.DateTimeFormat("en", { weekday: "long", day: "numeric", month: "long", timeZone: settings.timezone }).format(new Date())}</span>}/>
    <NextSession data={data}/>
    <div className="stats-grid"><StatCard label="Study streak" value={<>{streak.current} <span style={{ fontSize: 13, fontWeight: 400 }}>{streak.current === 1 ? "day" : "days"}</span></>} detail={streak.current ? "A little consistency goes a long way" : "Your first session starts your streak"} icon={<Flame size={17}/>} color="peach"/><StatCard label="Words learned" value={<>{vocabulary.learned} <span style={{ fontSize: 12, color: "var(--muted)", fontWeight: 400 }}>/ {vocabulary.total}</span></>} detail={`${vocabulary.mastered} mastered · ${vocabulary.learning} learning`} icon={<BookOpen size={17}/>}/><StatCard label="Ready for review" value={vocabulary.due} detail={vocabulary.due ? "Keep these words fresh in your memory" : "Your next review will appear here"} icon={<RotateCcw size={16}/>} color="purple"/><StatCard label="Study time today" value={<>{today.minutes > 0 && today.minutes < 1 ? "<1" : Math.round(today.minutes)} <span style={{ fontSize: 13, fontWeight: 400 }}>min</span></>} detail={`Your daily goal is ${settings.dailyStudyMinutes} minutes`} icon={<Clock3 size={17}/>} color="blue"/></div>
    <div className="dashboard-grid"><div className="stack"><section className="panel"><div className="panel-heading"><div><h2>Your focus for today</h2><p>A balanced little routine for a bigger goal.</p></div><span className="pill green">{activities.filter(item => completedModules.has(item.module)).length} of 4 practised</span></div>{activities.map(activity => <Link className="study-row" key={activity.href} href={activity.href}><span className={`icon-box ${activity.color}`}><activity.icon size={19}/></span><div className="study-row-content"><h3>{activity.title}</h3><p>{activity.description}</p></div><span className="study-duration">{activity.duration}</span><span className="round-arrow">{completedModules.has(activity.module) ? <Check size={13}/> : <ChevronRight size={13}/>}</span></Link>)}<div className="daily-footer"><Lightbulb size={13}/><span>{vocabulary.weak > 0 ? `${vocabulary.weak} words could use a little extra attention.` : "Consistency matters more than a perfect session."}</span>{vocabulary.weak > 0 && <Link href="/vocabulary/learn?source=weak" className="text-link" style={{ marginLeft: "auto" }}>Review <ArrowRight size={12}/></Link>}</div></section>
      <section className="panel"><div className="panel-heading"><div><h2>A week of showing up</h2><p>{stats.weeklyMinutes} minutes invested in yourself</p></div><span className="pill">Last 7 days</span></div><ActivityChart data={data.week}/><div className="chart-legend" style={{ marginTop: 18 }}><span><i className="legend-dot"/>Study minutes</span><span style={{ marginLeft: "auto" }}>{stats.weeklyMinutes === 0 ? "Your first session will bring this chart to life." : "Every focused minute counts."}</span></div></section>
    </div><div className="stack"><section className="panel"><div className="panel-heading"><h2>Your band goal</h2><Target size={17} color="var(--muted)"/></div><div className="target-ring"><svg viewBox="0 0 150 150" aria-hidden="true"><circle cx="75" cy="75" r="64" fill="none" stroke="var(--surface-alt)" strokeWidth="9"/><circle cx="75" cy="75" r="64" fill="none" stroke="#709581" strokeWidth="9" strokeLinecap="round" strokeDasharray={`${(data.estimatedOverall ?? 0) / 9 * 402} 402`}/></svg><div className="ring-text"><small>Working towards</small><strong>{settings.targetBand.toFixed(1)}</strong><small>IELTS Academic</small></div></div>{skills.map(([skill, estimate]) => <div key={skill}><div className="skill-score"><span>{skill}</span><b>{estimate === null ? "Not set" : estimate.toFixed(1)} <span className="muted" style={{ fontWeight: 400 }}>/ {settings.targetBand.toFixed(1)}</span></b></div><div className="progress-track" style={{ height: 4 }}><div className="progress-fill" style={{ width: `${Math.min(100, (estimate ?? 0) / settings.targetBand * 100)}%`, background: skill === "Writing" ? "#c4a179" : skill === "Speaking" ? "#a498bd" : "#81a28b" }}/></div></div>)}<div className="target-footnote">{data.estimatedOverall !== null ? `Your overall practice estimate: ${data.estimatedOverall.toFixed(1)}` : <Link href="/settings" className="text-link">Add your current score estimates <ArrowUpRight size={12}/></Link>}</div></section>
      {spotlight && <section className="panel word-spotlight"><div className="panel-heading" style={{ marginBottom: 11 }}><p className="eyebrow" style={{ marginBottom: 0 }}>A WORD TO TAKE WITH YOU</p><Sparkles size={15} color="#ae9674"/></div><h2 className="word">{spotlight.word}</h2><p className="small-note">{spotlight.partOfSpeech} · {spotlight.banglaMeaning}</p><p className="definition">{spotlight.definition}</p><p className="example">“{spotlight.ieltsExample}”</p><Link href={`/vocabulary?q=${spotlight.word}`} className="text-link">Make it part of your vocabulary <ArrowRight size={12}/></Link></section>}
    </div></div>
    <div className="section-heading"><h2>Make room for every skill</h2><Link href="/resources" className="text-link">Explore your library <ArrowUpRight size={13}/></Link></div><div className="module-grid">{[{ title: "Speak with confidence", text: "Find your ideas. Make them heard.", href: "/speaking", icon: Mic, color: "peach", cta: "Start speaking" }, { title: "Write with purpose", text: "Clear thinking, one paragraph at a time.", href: "/writing", icon: NotebookPen, color: "purple", cta: "Open your workspace" }, { title: "Read with curiosity", text: "Notice the details. Find the evidence.", href: "/reading", icon: BookOpen, color: "blue", cta: "Explore passages" }, { title: "Build your foundations", text: "Small grammar fixes. Clearer English.", href: "/grammar", icon: SpellCheck, color: "green", cta: "Practise grammar" }].map(module => <Link key={module.href} href={module.href} className="module-card"><span className={`icon-box ${module.color}`}><module.icon size={18}/></span><h3>{module.title}</h3><p>{module.text}</p><span className="text-link">{module.cta} <ArrowRight size={12}/></span></Link>)}</div>
  </>;
}
