"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { categoryNames, realDifficulty, type ReadingCategory } from "@/lib/reading/categories";
import { readingLessons } from "@/lib/reading/lessons";
import type { ReadingCatalog } from "@/lib/reading/service";
import type { Attempt } from "@/lib/reading/model";
import { request, label, formatDate } from "@/lib/client";
import { time, message } from "@/components/practice/shared";
import { ErrorNotice } from "@/components/ui";

const href=(category:string,layer:string)=>`/reading?category=${category}&layer=${layer}`;
export function ReadingLayersOverview({catalog}:{catalog:ReadingCatalog}){
  const continuing=catalog.attempts.find(a=>!a.completedAt),real=catalog.layers.filter(l=>l.real.recentAccuracy!==null).sort((a,b)=>a.real.recentAccuracy!-b.real.recentAccuracy!)[0];
  const full=new Set(catalog.attempts.filter(a=>a.mockTestId&&a.completedAt).map(a=>a.mockTestId)).size;
  return <section className="panel reading-layers-home"><p className="eyebrow">Learn → Practice → Real Practice → Full Mock Test</p><h2>Your Reading path</h2><p>Target 7.5. Learn the method, develop the skill, then test it on a full-length task without hints.</p><div className="reading-layer-summary"><div><strong>{real?.real.recentAccuracy===undefined?'—':`${real.real.recentAccuracy}%`}</strong><span>Recent accuracy in your weakest Real Practice family</span></div><div><strong>{real?categoryNames[real.questionFamily]:'Build your baseline'}</strong><span>Weakest Real Practice family</span></div><div><strong>{full} / 15</strong><span>Full tests completed · {catalog.mocks.length} available</span></div></div>
    {continuing&&<a className="button primary" href={`/reading?attempt=${continuing.id}`}>Continue Reading · {label(continuing.practiceType)}</a>}
    <div className="reading-path-table" aria-label="Reading question types"><div className="reading-path-row reading-path-head"><span>Question Type</span><span>Skill Practice</span><span>Real Practice</span><span>Progress</span></div>{catalog.layers.map(l=><div className="reading-path-row" key={l.questionFamily}><a className="text-link" href={href(l.questionFamily,'learn')}>{categoryNames[l.questionFamily]}</a><a href={href(l.questionFamily,'practice')}>Skill: {l.skill.completed}/25 complete<small>{l.skill.available} available</small></a><a href={href(l.questionFamily,'real')}>Real: {l.real.completed}/25 complete<small>{l.real.available} available</small></a><span>Skill {l.skill.progress}%<br/>Real {l.real.progress}%</span></div>)}</div>
    <p className="small-note">25 sets per layer and 15 mocks are library targets. Available counts show the content you can use today. Yes / No / Not Given is retained with the information-and-claims lessons and in the existing skill library.</p><a className="button" href="/reading?tab=mocks">Full Mock Tests · {catalog.mocks.length} available / 15 planned</a>
  </section>;
}
export function ReadingCategoryPage({catalog,category,layer}:{catalog:ReadingCatalog;category:ReadingCategory;layer:string}){
  const current=['learn','practice','real'].includes(layer)?layer:'learn';const progress=catalog.layers.find(l=>l.questionFamily===category)!;
  return <section className="reading-category"><a href="/reading" className="text-link">← Reading home</a><h2>{categoryNames[category]}</h2><nav className="writing-tabs" aria-label="Learning layers">{[['learn','Learn'],['practice','Practice'],['real','Real Practice']].map(([key,title])=><a key={key} className={current===key?'active':''} aria-current={current===key?'page':undefined} href={href(category,key)}>{title}</a>)}</nav>
    <div className="reading-layer-summary"><div><strong>{progress.skill.completed} / 25</strong><span>Skill Practice · {progress.skill.available} available</span></div><div><strong>{progress.real.completed} / 25</strong><span>Real Practice · {progress.real.available} available</span></div><div><strong>{progress.real.accuracy===null?'—':`${progress.real.accuracy}%`}</strong><span>Real accuracy · recent {progress.real.recentAccuracy===null?'—':`${progress.real.recentAccuracy}%`}</span></div><div><strong>{progress.real.weakness?label(progress.real.weakness):'No recorded weakness'}</strong><span>Most frequent Real Practice mistake</span></div></div>
    {current==='learn'?<ReadingLearn category={category}/>:current==='real'?<RealPracticeLibrary catalog={catalog} category={category}/>:<section className="panel"><h3>Progressive Skill Practice</h3><p>Sets 1–5 Foundation · 6–10 Developing · 11–17 Exam · 18–25 Advanced / Band 7.5 Target.</p><p>Use learning mode for optional hints, paragraph and keyword support, or timed exam mode for independent practice.</p><PracticeSetList catalog={catalog} category={category} real={false}/><a href="/reading?tab=library" className="text-link">Browse all existing skill sets and seven original families →</a></section>}
  </section>;
}
function ReadingLearn({category}:{category:ReadingCategory}){
  const lesson=readingLessons[category];return <section className="panel reading-learn"><h3>Learn the method</h3><p>{lesson.meaning}</p><h4>How the task is asked</h4><p>{lesson.instructions}</p><h4>Step by step</h4><ol>{lesson.steps.map(step=><li key={step}>{step}</li>)}</ol><h4>Common traps</h4><ul>{lesson.traps.map(trap=><li key={trap}>{trap}</li>)}</ul><h4>Worked example</h4><blockquote>{lesson.worked.passage}</blockquote><p>{lesson.worked.question}</p><p><strong>Answer: {lesson.worked.answer}</strong></p><p>{lesson.worked.explanation}</p><h4>Try two mini questions</h4>{lesson.minis.map((mini,i)=><MiniQuestion key={category+i} mini={mini} number={i+1}/>)}<h4>Build towards 7.5</h4><ul>{lesson.tips.map(tip=><li key={tip}>{tip}</li>)}</ul><a className="button primary" href={href(category,'practice')}>Continue to Practice</a></section>;
}
function MiniQuestion({mini,number}:{mini:typeof readingLessons.COMPLETION.worked;number:number}){const [answer,setAnswer]=useState(''),[checked,setChecked]=useState(false);return <article className="reading-mini"><blockquote>{mini.passage}</blockquote><label>Mini question {number}: {mini.question}<select aria-label={`Mini answer ${number}`} value={answer} onChange={e=>{setAnswer(e.target.value);setChecked(false);}}><option value="">Choose</option>{mini.options.map(o=><option key={o}>{o}</option>)}</select></label><button className="button small" disabled={!answer} onClick={()=>setChecked(true)}>Check mini answer {number}</button>{checked&&<p role="status"><strong>{answer===mini.answer?'Correct.':'Review this answer.'}</strong> {mini.explanation}</p>}</article>;}
export function RealPracticeLibrary({catalog,category}:{catalog:ReadingCatalog;category?:ReadingCategory}){return <section className="panel"><p className="eyebrow">Real Practice</p><h3>Independent IELTS-style tasks</h3><p>Original academic-style passages, one selected family per set. A fixed 20-minute timer continues when you leave. Answers, evidence and explanations unlock after submission.</p><p className="small-note">Progression target: 01–05 Moderate · 06–10 Normal Exam · 11–15 Exam · 16–20 Strong Exam · 21–25 Band 7.5 Target.</p><PracticeSetList catalog={catalog} category={category} real/><RealPracticeHistory catalog={catalog} category={category}/></section>;}
function PracticeSetList({catalog,category,real}:{catalog:ReadingCatalog;category?:ReadingCategory;real:boolean}){
  const router=useRouter(),keys=useRef<Record<string,string>>({});const [busy,setBusy]=useState(''),[error,setError]=useState(''),[style,setStyle]=useState('all');
  const sets=catalog.passages.filter(p=>p.practiceType===(real?'REAL_PRACTICE':'SKILL_PRACTICE')&&(!category||p.questionFamily===category));
  async function start(id:string){setBusy(id);setError('');try{const a=await request<Attempt>('/api/reading?action=start',{passageId:id,clientKey:keys.current[id]??(keys.current[id]=crypto.randomUUID())});router.push(`/reading?attempt=${a.id}`);}catch(e){setError(message(e));setBusy('');}}
  return <><ErrorNotice message={error}/>{real&&<label className="reading-style-filter">Style / topic<select value={style} onChange={e=>setStyle(e.target.value)}><option value="all">All styles</option>{[...new Set(sets.map(p=>p.sourceStyle))].map(s=><option key={s}>{s}</option>)}</select></label>}<div className="reading-real-grid">{sets.filter(p=>style==='all'||p.sourceStyle===style).map(p=>{
    const runs=catalog.attempts.filter(a=>a.passageId===p.id&&a.practiceType===p.practiceType&&!a.focusedRetry&&(!real||!a.assisted)),finished=runs.filter(a=>a.completedAt),last=finished[0],active=runs.find(a=>!a.completedAt),best=[...finished].sort((a,b)=>b.score-a.score)[0];
    return <article className="reading-set-card" key={p.id}><p className="eyebrow">{real?'Real Practice':'Skill Practice'} {String(p.setNumber).padStart(2,'0')} · {categoryNames[p.questionFamily as ReadingCategory]}</p><h4>{p.title}</h4><p>{p.topic} · {real?realDifficulty(p.setNumber):label(p.difficultyLevel)}<br/>{p.wordCount} words · {p.questions.length} questions · {p.timeLimitMinutes} minutes</p><dl><div><dt>Status</dt><dd>{active?'In progress':last?'Completed':'Not started'}</dd></div><div><dt>Previous score</dt><dd>{last?`${last.raw}/${last.total} (${last.score}%)`:'—'}</dd></div><div><dt>Best score</dt><dd>{best?`${best.raw}/${best.total} (${best.score}%)`:'—'}</dd></div><div><dt>Last attempt</dt><dd>{runs[0]?formatDate(runs[0].startedAt):'—'}</dd></div></dl>{real?<button className="button primary" disabled={!!busy} onClick={()=>void start(p.id)}>{busy===p.id?'Opening…':active?'Resume Real Practice':last?'Start Again':'Start Real Practice'}</button>:<a className="button" href={`/reading?id=${p.id}`}>Open Skill Practice</a>}{last&&<a className="text-link" href={`/reading?attempt=${last.id}`}>Review previous attempt</a>}</article>;
  })}</div>{!sets.length&&<p className="notice">No {real?'Real Practice':'Skill Practice'} sets are published in this category yet. The category and its 25-set target remain part of the plan. {real?'Use Learn and the existing Skill Practice while this bank expands.':'Other skill sets remain available in the full library.'}</p>}{sets.length>0&&!sets.some(p=>style==='all'||p.sourceStyle===style)&&<p>No sets match this style.</p>}</>;
}
export function RealPracticeHistory({catalog,category}:{catalog:ReadingCatalog;category?:ReadingCategory}){
  const runs=catalog.attempts.filter(a=>a.practiceType==='REAL_PRACTICE'&&(!category||a.questionFamily===category));
  return <section className="reading-real-history"><h3>Real Practice history</h3><p>Every submitted attempt is retained. Repeating familiar content can improve scores through memory as well as skill.</p>{runs.map(a=>{const alternative=catalog.passages.find(p=>p.id!==a.passageId&&p.questionFamily===a.questionFamily&&p.practiceType==='REAL_PRACTICE')??catalog.passages.find(p=>p.id!==a.passageId&&p.questionFamily===a.questionFamily&&p.practiceType==='SKILL_PRACTICE');return <article className="reading-history-row" key={a.id}><strong>{a.passage.title}</strong><p>{categoryNames[a.questionFamily as ReadingCategory]} · {formatDate(a.startedAt)} · {time(a.durationSeconds)}<br/>{a.completedAt?`${a.raw}/${a.total} · ${a.score}%`:'In progress'}</p>{Object.entries(a.mistakeCounts).length>0&&<p>Mistakes: {Object.entries(a.mistakeCounts).map(([type,count])=>`${count} ${label(type)}`).join(' · ')}</p>}<div className="toolbar"><a className="button small" href={`/reading?attempt=${a.id}`}>{a.completedAt?'Review':'Resume'}</a>{a.completedAt&&<a className="button small" href={`/reading?id=${a.passageId}`}>Retry set</a>}{alternative&&<a className="button small" href={`/reading?id=${alternative.id}`}>Practice similar set{alternative.practiceType==='SKILL_PRACTICE'?' · Skill Practice':''}</a>}</div></article>;})}{!runs.length&&<p>No Real Practice attempts yet.</p>}</section>;
}
export function RealPracticeStart({catalog,id,onStart,busy}:{catalog:ReadingCatalog;id:string;onStart:()=>void;busy:boolean}){const p=catalog.passages.find(p=>p.id===id)!;return <section className="panel"><a className="text-link" href={href(p.questionFamily,'real')}>← {categoryNames[p.questionFamily as ReadingCategory]} / Real Practice</a><p className="eyebrow">Real Practice {String(p.setNumber).padStart(2,'0')} · {realDifficulty(p.setNumber)}</p><h2>{p.title}</h2><p>{p.wordCount} words · {p.questions.length} questions · {p.timeLimitMinutes} minutes</p><p>Work independently. Submit the whole set to unlock answers, exact evidence, paraphrase connections and mistake analysis. Your timer continues after leaving or reloading.</p><button className="button primary" disabled={busy} onClick={onStart}>Start / resume Real Practice</button></section>;}
