"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState, useRef } from "react";
import { BookOpen, ArrowRight, Clock } from "lucide-react";
import { request, label, formatDate } from "@/lib/client";
import { ErrorNotice } from "@/components/ui";
import { PracticeLoadState, message, time } from "@/components/practice/shared";
import type { ReadingCatalog } from "@/lib/reading/service";
import { familyNames, levels, type Attempt } from "@/lib/reading/model";
import { ReadingWorkspace } from "./workspace";
import { PriorityPractice } from "./priority-practice";
import { ReadingSource } from "./matching-group";
import { ReadingImport } from "./tools";
import { ReadingLayersOverview, ReadingCategoryPage, RealPracticeLibrary, RealPracticeHistory, RealPracticeStart } from "./layers";
import { readingCategories, type ReadingCategory } from "@/lib/reading/categories";
import { ReadingTrainers } from "./trainers";

export function ReadingStudio({initialId,initialAttempt,initialFocus,category,layer="learn",tab="home"}:{initialId?:string;initialAttempt?:string;initialFocus?:string;category?:string;layer?:string;tab?:string}){
  const router=useRouter();
  const [catalog,setCatalog]=useState<ReadingCatalog|null>(null),[attempt,setAttempt]=useState<Attempt|null>(null),[error,setError]=useState("");
  const [reload,setReload]=useState(0),[busy,setBusy]=useState(false),[family,setFamily]=useState("all"),[level,setLevel]=useState("all"),[search,setSearch]=useState("");
  const [focus,setFocus]=useState(initialFocus??"");
  const [mode,setMode]=useState("LEARNING"),[minutes,setMinutes]=useState(20),[clientKey]=useState(()=>crypto.randomUUID());
  useEffect(()=>{let active=true;Promise.all([request<ReadingCatalog>("/api/reading"),initialAttempt?request<Attempt>(`/api/reading?attemptId=${encodeURIComponent(initialAttempt)}`):Promise.resolve(null)]).then(([c,a])=>{if(active){setCatalog(c);setAttempt(a);}}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;};},[initialAttempt,reload]);
  if(!catalog)return <PracticeLoadState error={error} onRetry={()=>{setError("");setReload(n=>n+1);}}/>;
  if(initialAttempt&&!attempt)return <PracticeLoadState error={error} onRetry={()=>{setError("");setReload(n=>n+1);}}/>;
  if(attempt)return <ReadingWorkspace initial={attempt} key={attempt.id}/>;
  async function start(passageId?:string,mockTestId?:string){setBusy(true);setError("");try{const a=await request<Attempt>("/api/reading?action=start",{passageId,mockTestId,mode,minutes,clientKey,...(passageId&&focus?{focusType:focus}:{})});router.push(`/reading?attempt=${a.id}`);}catch(e){setError(message(e));setBusy(false);}}
  const selected=catalog.passages.find(p=>p.id===initialId);
  const filtered=catalog.passages.filter(p=>p.practiceType==="SKILL_PRACTICE"&&(family==="all"||p.family===family)&&(level==="all"||p.difficultyLevel===level)&&`${p.title} ${p.topic}`.toLowerCase().includes(search.toLowerCase()));
  const continuing=catalog.attempts.find(a=>!a.completedAt);
  const completed=catalog.attempts.filter(a=>a.completedAt);
  const tabs=[['home','Overview'],['practice','Question types'],['real','Real Practice'],['library','Skill library'],['mocks','Full tests'],['history','History'],['real-history','Real history'],['weaknesses','Weaknesses'],['mistakes','Mistake notebook'],['trainers','Skill trainers'],['import','Import passage'],['starter','Starter history']];
  return <div className="reading-studio"><nav className="writing-tabs" aria-label="Reading sections">{tabs.map(([id,title])=><a href={`/reading${id==='home'?'':`?tab=${id}`}`} className={tab===id?'active':''} key={id}>{title}</a>)}</nav><ErrorNotice message={error}/>
    {selected?.practiceType==="REAL_PRACTICE"?<RealPracticeStart catalog={catalog} id={selected.id} busy={busy} onStart={()=>void start(selected.id)}/>:selected?<section className="panel"><p className="eyebrow">{familyNames[selected.family]} · {label(selected.difficultyLevel)}</p><h2>{selected.title}</h2><p>{selected.wordCount} words · {selected.questions.length} questions · Passage {selected.passageNumberEquivalent} equivalent</p><ReadingSource source={selected.source}/><p>Learning mode lets you ask for hints and check individual answers. Exam mode hides all help and uses a fixed deadline that continues when you leave.</p><div className="toolbar"><label>Start with task<select aria-label="Start with task" value={focus} onChange={e=>setFocus(e.target.value)}><option value="">First task</option>{[...new Set(selected.questions.map(q=>q.type))].map(type=><option key={type} value={type}>{label(type)}</option>)}</select></label><label>Practice mode<select aria-label="Practice mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="LEARNING">Learning · untimed</option><option value="EXAM">Exam · timed</option></select></label>{mode==="EXAM"&&<label>Minutes<input type="number" min={1} max={120} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label>}<button className="button primary" disabled={busy||!Number.isInteger(minutes)||minutes<1||minutes>120} onClick={()=>void start(selected.id)}>Start / resume practice<ArrowRight size={15}/></button></div><p className="small-note">If you already have an unfinished attempt in this mode, this resumes your saved position. Use the Task group menu inside to switch tasks. At an exam deadline, the latest server-saved answers are finalised. No extra transfer time.</p></section>
    :category&&readingCategories.includes(category as ReadingCategory)?<ReadingCategoryPage catalog={catalog} category={category as ReadingCategory} layer={layer}/>
    :tab==="real"?<RealPracticeLibrary catalog={catalog}/>
    :tab==="real-history"?<RealPracticeHistory catalog={catalog}/>
    :tab==="import"?<ReadingImport/>
    :tab==="trainers"?<ReadingTrainers/>
    :tab==="mistakes"?<ReadingMistakes catalog={catalog}/>
    :tab==="history"?<section className="panel"><h2>Your reading history</h2><p>Each completed attempt keeps its own passage, question, answer and evidence snapshot.</p>{catalog.attempts.map(a=><div className="study-row" key={a.id}><div className="study-row-content"><h3>{a.mockTestId?'Full Reading test':a.passage.title}</h3><p>{formatDate(a.startedAt)} · {label(a.practiceType)} ? {a.mode==='EXAM'?'Exam':'Learning'}{a.assisted?' · assisted':''} · {a.completedAt?`${a.raw}/${a.total} · ${a.score}% · ${time(a.durationSeconds)}`:'In progress'}</p></div><a className="button" href={`/reading?attempt=${a.id}`}>{a.completedAt?'Review':'Resume'}</a></div>)}{!catalog.attempts.length&&<p>No attempts yet. Choose a question family to begin.</p>}</section>
    :tab==="weaknesses"?<ReadingWeaknesses catalog={catalog}/>
    :tab==="mocks"?<><section className="panel"><h2>Full Academic Reading tests</h2><p>{new Set(completed.filter(a=>a.mockTestId).map(a=>a.mockTestId)).size}/{catalog.mocks.length} available tests completed · library target: 15 tests</p><p>Three separate passages, 40 marks, 60 minutes. The clock continues after reload or leaving the page. At timeout, the last server-saved version becomes your result; late edits remain downloadable locally.</p><p className="small-note">These original practice texts are separate from targeted sets. The first full test contains 2,405 words and increases in difficulty across its three passages.</p></section>{catalog.mocks.map(m=><section className="panel" key={m.id}><span className="icon-box peach"><Clock size={21}/></span><h2>{m.title}</h2><p>60 minutes · 3 passages · 40 questions · no hints</p><button className="button primary" disabled={busy} onClick={()=>void start(undefined,m.id)}>Start / resume full test</button></section>)}<BandProgress catalog={catalog}/></>
    :<>{(tab==="home"||tab==="practice")&&<ReadingLayersOverview catalog={catalog}/>}<PriorityPractice/>{tab==="home"&&<><div className="reading-hero"><div><p className="eyebrow">Read for meaning. Find the proof.</p><h2>Build accuracy before speed.</h2><p>Train the skill behind each question, see exactly which words support the answer, and choose your next practice from real results.</p></div><div><strong>{catalog.passages.filter(p=>p.practiceType==='SKILL_PRACTICE'&&p.sourceType!=='IMPORTED').length}</strong><span>targeted sets available</span><strong>{catalog.mocks.length}</strong><span>complete mock available</span></div></div>{continuing&&<section className="panel"><p className="eyebrow">Continue practice</p><h2>{continuing.mockTestId?'Your unfinished full test':continuing.passage.title}</h2><a className="button primary" href={`/reading?attempt=${continuing.id}`}>Resume your answers<ArrowRight size={15}/></a></section>}<section className="panel"><h2>Today’s reading</h2>{catalog.recommendations.map(r=><div className="study-row" key={r.id}><div className="study-row-content"><h3>{r.title}</h3><p>{r.reason}</p></div><a className="button" href={`/reading?id=${r.id}`}>Practise</a></div>)}</section></>}
      <section><h2>Practice by question type</h2><p className="small-note">The Gold Set validates all question types before expansion. Each family targets 25 distinct sets; available counts below reflect what you can open now.</p><div className="reading-family-grid">{catalog.familyStats.map(stat=><button key={stat.family} className={`panel reading-family ${family===stat.family?'selected':''}`} onClick={()=>setFamily(stat.family)} aria-pressed={family===stat.family}><BookOpen size={21}/><h3>{familyNames[stat.family]}</h3><strong>{stat.completed} / 25 completed</strong><p>{stat.available} curated sets available</p><p>{stat.accuracy===null?'No results yet':`${stat.accuracy}% accuracy · recent ${stat.recentAccuracy}%`}</p><p>{time(stat.averageTime)} average · {stat.needsReview} to review</p><small>{stat.difficultyReached?`Recent level: ${label(stat.difficultyReached)}`:'Build your first result'}</small></button>)}</div></section>
      <section className="panel"><div className="toolbar"><label>Family<select aria-label="Reading family" value={family} onChange={e=>setFamily(e.target.value)}><option value="all">All families</option>{Object.entries(familyNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>Level<select aria-label="Reading level" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">All levels</option>{levels.map(l=><option key={l} value={l}>{label(l)}</option>)}</select></label><label>Search passages<input value={search} onChange={e=>setSearch(e.target.value)}/></label></div><p className="small-note">Foundation → Developing → Exam → Advanced. Short focused sets develop one skill; the longer mixed set and full mock build exam endurance.</p>{filtered.map(p=><div className="study-row" key={p.id}><div className="study-row-content"><h3>{p.title}</h3><p>{familyNames[p.family]} · {label(p.difficultyLevel)} · {p.wordCount} words · {p.questions.length} questions{p.sourceType==='PUBLIC_DOMAIN'?' ? Real text / new questions':p.sourceType==='IMPORTED'?' · Your import':''}</p></div><a className="button" href={`/reading?id=${p.id}`}>Open set<ArrowRight size={14}/></a></div>)}{!filtered.length&&<p>No sets match these filters. More content can be added through imports or later curated releases.</p>}</section>{tab==="home"&&<><BandProgress catalog={catalog}/><section className="panel"><h2>Recent results</h2>{completed.slice(0,5).map(a=><p key={a.id}><a className="text-link" href={`/reading?attempt=${a.id}`}>{a.passage.title} · {a.raw}/{a.total} · {formatDate(a.startedAt)}</a></p>)}{!completed.length&&<p>Your saved results will appear here.</p>}</section></>}
    </>}
    <p className="small-note">Original exercises and attributed public-domain extracts · <a href="https://ielts.org/take-a-test/test-types/ielts-academic-test/ielts-academic-format-reading" target="_blank" rel="noreferrer">Official Academic Reading format</a> · practice estimates are not official results.</p>
  </div>;
}
function BandProgress({catalog}:{catalog:ReadingCatalog}){
  const results=catalog.lastMocks,average=results.length?results.reduce((n,a)=>n+a.raw,0)/results.length:0;
  const trend=results.length>1?results[0].raw-results.at(-1)!.raw:0;
  return <section className="panel"><h2>Your 7.5 reading target</h2><p>Use several full tests to judge consistency. Learning-mode and short-set results are excluded.</p>{results.length?<><p>Last {results.length} full tests: {results.map(a=>`${a.raw}/40`).join(' · ')}</p><p>Average {average.toFixed(1)}/40 · range {Math.min(...results.map(a=>a.raw))}–{Math.max(...results.map(a=>a.raw))} · {results.length>1?`${trend>0?'+':''}${trend} marks from oldest to latest`:'More tests needed for a trend'}</p><p>{results.filter(a=>(a.band??0)>=7.5).length}/{results.length} attempts at an estimated practice band of at least 7.5.</p></>:<p>No completed full tests yet. There is not enough evidence to estimate readiness.</p>}{results.length<5&&<p className="small-note">Fewer than five completed full tests: treat the current sample as provisional. Repeating the same test may reflect familiarity.</p>}</section>;
}
function ReadingWeaknesses({catalog}:{catalog:ReadingCatalog}){return <section className="panel"><h2>Where to focus next</h2><p>Based on the latest 30 answered question records from completed practices. Learning, exam and repeat attempts can all contribute; this is a training signal, not a band estimate.</p>{catalog.byType.map(t=><div className="study-row" key={t.type}><strong>{label(t.type)}</strong><span>{t.correct}/{t.total} marks · {Math.round(t.correct/t.total*100)}%</span></div>)}{!catalog.byType.length&&<p>Complete a practice to establish your baseline.</p>}<h3>Recommended practice</h3>{catalog.recommendations.map(r=><p key={r.id}><a href={`/reading?id=${r.id}`} className="text-link">{r.title}</a><br/>{r.reason}</p>)}</section>;}
function ReadingMistakes({catalog}:{catalog:ReadingCatalog}){
  const router=useRouter(); const actionKeys=useRef<Record<string,string>>({});
  const [items,setItems]=useState(catalog.mistakes),[category,setCategory]=useState('all'),[status,setStatus]=useState('unresolved'),[date,setDate]=useState(''),[type,setType]=useState('all'),[level,setLevel]=useState('all'),[error,setError]=useState('');
  const shown=items.filter(m=>{const attempt=catalog.attempts.find(a=>m.sourceId.startsWith(`${a.id}:`));return(type==='all'||m.questionType===type)&&(category==='all'||m.category===category)&&(status==='all'||m.resolved===(status==='resolved'))&&(!date||new Date(m.createdAt).toLocaleDateString('en-CA',{timeZone:catalog.timezone})===date)&&(level==='all'||attempt?.passage.difficultyLevel===level);});
  return <section className="panel"><h2>Your reading mistakes</h2><div className="toolbar"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(items.map(m=>m.category))].map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="unresolved">Needs revision</option><option value="resolved">Resolved</option><option value="all">All</option></select></label><label>Question type<select value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option>{[...new Set(items.map(m=>m.questionType))].map(t=><option key={t} value={t}>{label(t)}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Difficulty<select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">All levels</option>{levels.map(l=><option key={l}>{l}</option>)}</select></label></div><ErrorNotice message={error}/>{shown.map(m=>{const attempt=catalog.attempts.find(a=>m.sourceId.startsWith(`${a.id}:`));const similar=m.similar;return <article className="reading-mistake" key={m.id}><span className="pill">{label(m.category)}</span><p style={{whiteSpace:'pre-wrap'}}>{m.originalContent}</p><p><strong>Correction:</strong> {m.correction}</p><p>{m.explanation}</p><div className="toolbar">{attempt&&<><a className="button small" href={`/reading?attempt=${attempt.id}`}>Review passage</a><button className="button small" onClick={async()=>{try{const a=await request<Attempt>("/api/reading?action=retry",{attemptId:attempt.id,questionId:m.questionId,clientKey:actionKeys.current[`${m.id}:retry`]??(actionKeys.current[`${m.id}:retry`]=crypto.randomUUID())});router.push(`/reading?attempt=${a.id}`);}catch(e){setError(message(e));}}}>Retry this question</button></>}{similar&&<button className="button small" onClick={async()=>{try{const a=await request<Attempt>("/api/reading?action=start",{passageId:similar.passageId,questionId:similar.questionId,clientKey:actionKeys.current[`${m.id}:similar`]??(actionKeys.current[`${m.id}:similar`]=crypto.randomUUID())});router.push(`/reading?attempt=${a.id}`);}catch(e){setError(message(e));}}}>Practise similar question</button>}<button className="button small" onClick={async()=>{try{const updated=await request<typeof m>(`/api/mistakes/${m.id}`,{resolved:!m.resolved},'PATCH');setItems(current=>current.map(item=>item.id===m.id?{...item,...updated}:item));}catch(e){setError(message(e));}}}>{m.resolved?'Reopen':'Mark resolved'}</button></div></article>;})}{!shown.length&&<p>No mistakes match these filters.</p>}</section>;
}
