"use client";
import { useState } from "react";
import { request } from "@/lib/client";
import { message, useUnsavedWork } from "@/components/practice/shared";
import { ErrorNotice } from "@/components/ui";
export function ReadingImport(){
  const [text,setText]=useState(''),[rights,setRights]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<{title:string;words:number;questions:number}|null>(null),[saved,setSaved]=useState(''),[key,setKey]=useState(()=>crypto.randomUUID());
  useUnsavedWork(!!text&&!saved);
  async function submit(save:boolean){setBusy(true);setError('');try{const passage=JSON.parse(text);const result=await request<{id?:string;title:string;words:number;questions:number}>('/api/reading?action=import',{passage,save,rightsConfirmed:rights,clientKey:key});if(result.id)setSaved(result.id);else setPreview(result);}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <section className="panel"><h2>Import your own passage</h2><p>Paste a structured passage with its title, source, paragraph text, questions, answer key and evidence. You can edit the downloadable template or load a JSON file. Only material you have permission to use is imported.</p><a className="button" href="/api/reading/template" download="reading-import-template.json">Download editable JSON template</a><label>Load passage JSON<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(file){if(file.size>900000){setError('Keep the file below 900 KB.');return;}setText(await file.text());setPreview(null);setSaved('');setKey(crypto.randomUUID());}}}/></label><label>Passage and questions JSON<textarea aria-label="Passage and questions JSON" rows={18} value={text} onChange={e=>{setText(e.target.value);setPreview(null);setSaved('');setKey(crypto.randomUUID());}}/></label><ErrorNotice message={error}/><button className="button" disabled={busy||!text} onClick={()=>void submit(false)}>Validate and preview</button>{preview&&<div className="notice"><strong>{preview.title}</strong><p>{preview.words} words · {preview.questions} questions</p><p>Structure, word limits and exact evidence locations passed. You remain responsible for checking that answers are unambiguous and explanations match the passage.</p><label className="checkbox-label"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>I have permission to use this material for my study.</label><button className="button primary" disabled={busy||!rights||!!saved} onClick={()=>void submit(true)}>Save imported passage</button></div>}{saved&&<p role="status">Passage saved. <a className="text-link" href={`/reading?id=${saved}`}>Open your imported practice →</a></p>}</section>;
}
