"use client";
import { useEffect,useState } from "react";
import type { Drill } from "@/lib/reading/trainers";
import { request,formatDate,label } from "@/lib/client";
import { message,time,useUnsavedWork } from "@/components/practice/shared";
import { ErrorNotice } from "@/components/ui";
export function ReadingTrainers(){const [history,setHistory]=useState<Drill[]>([]),[selected,setSelected]=useState<Drill|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[key,setKey]=useState(()=>crypto.randomUUID());useEffect(()=>{request<Drill[]>('/api/reading/trainers').then(setHistory).catch(e=>setError(message(e)));},[]);
  if(selected)return <DrillEditor key={selected.id} initial={selected} onSaved={a=>setHistory(h=>[a,...h.filter(item=>item.id!==a.id)])} onClose={()=>setSelected(null)}/>;
  return <div className="stack"><section className="panel"><h2>Train the smaller reading skills</h2><p>Recognise paraphrases, skim for purpose, and scan for precise information. Results and elapsed time are saved separately from full-test readiness.</p><ErrorNotice message={error}/><div className="toolbar">{[['KEYWORD','Find the paraphrase'],['SKIMMING','60-second skimming'],['SCANNING','Timed scanning']].map(([kind,title])=><button className="button" key={kind} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setSelected(await request<Drill>('/api/reading/trainers?action=start',{kind,clientKey:key}));setKey(crypto.randomUUID());}catch(e){setError(message(e));}finally{setBusy(false);}}}>{title}</button>)}</div></section><section className="panel"><h2>Trainer history</h2>{history.map(a=><div className="study-row" key={a.id}><div className="study-row-content"><h3>{label(a.kind)} · {a.title}</h3><p>{formatDate(a.startedAt)} · {a.completedAt?`${a.isCorrect?'Correct':'Needs review'} · ${time(a.durationSeconds)}`:'In progress'}</p></div><button className="button" onClick={async()=>{try{const fresh=await request<Drill[]>("/api/reading/trainers");setHistory(fresh);setSelected(fresh.find(item=>item.id===a.id)??null);}catch(e){setError(message(e));}}}>{a.completedAt?'Review':'Resume'}</button></div>)}{!history.length&&<p>No trainer attempts yet.</p>}</section></div>;
}
function DrillEditor({initial,onSaved,onClose}:{initial:Drill;onSaved:(a:Drill)=>void;onClose:()=>void}){const [attempt,setAttempt]=useState(initial),[answer,setAnswer]=useState(initial.userAnswer),[busy,setBusy]=useState(false),[error,setError]=useState('');const [now,setNow]=useState(()=>Date.now());const [offset]=useState(()=>Date.parse(initial.serverTime)-Date.now());useUnsavedWork(!!answer&&!attempt.completedAt);useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(id);},[]);const seconds=Math.max(0,Math.floor((now+offset-Date.parse(attempt.startedAt))/1000));const show=attempt.kind!=='SKIMMING'||seconds<60||!!attempt.completedAt;
 return <section className="panel"><button className="button" onClick={()=>{if(!answer||attempt.completedAt||window.confirm('Leave without submitting your trainer answer?'))onClose();}}>Trainer history</button><h2>{attempt.title}</h2><p>{attempt.kind==='SKIMMING'&&!attempt.completedAt?`${Math.max(0,60-seconds)} seconds of passage viewing remain. Reloading does not restart the window.`:`Elapsed: ${time(attempt.completedAt?attempt.durationSeconds:seconds)}`}</p>{attempt.content&&show?<div className="reading-trainer-passage">{attempt.content}</div>:attempt.kind==='SKIMMING'&&<p className="notice">The viewing window has ended. Answer from the structure you noticed.</p>}<h3>{attempt.prompt}</h3>{attempt.options.length?<fieldset disabled={busy||!!attempt.completedAt}>{attempt.options.map(option=><label className="reading-option" key={option}><input type="radio" name="trainer-answer" value={option} checked={answer===option} onChange={()=>setAnswer(option)}/>{option}</label>)}</fieldset>:<label>Your answer<input aria-label="Trainer answer" value={answer} disabled={busy||!!attempt.completedAt} onChange={e=>setAnswer(e.target.value)}/></label>}<ErrorNotice message={error}/>{!attempt.completedAt&&<button className="button primary" disabled={busy||!answer.trim()} onClick={async()=>{setBusy(true);try{const result=await request<Drill>('/api/reading/trainers?action=answer',{id:attempt.id,answer});setAttempt(result);onSaved(result);}catch(e){setError(message(e));}finally{setBusy(false);}}}>Submit trainer answer</button>}{attempt.completedAt&&<div className="notice" role="status"><strong>{attempt.isCorrect?'Correct':'Needs review'}</strong><p>Correct answer: {attempt.answer}</p><p>{attempt.explanation}</p></div>}</section>;
}
